### ISSUE TITLE
IUniV3Automan ran out of gas

### ISSUE THREAD

**Issue by cosullivan** [Aperture-Finance/uniswap-v3-automan#41]
Hi,

I'm trying to optimally mint positions using IUniV3Automan (0x00000000ede6d8d217c60f93191c060747324bca) on Ethereum (a fork via hardhat) and running into some issues with it running out of gas. 

I'm not sure if theres an issue somewhere in the `getOptimalSwap` or with how I am trying to use it.

I create a new pool with the medium fee, and I can use the `NonfungiblePositionManager` to mint the following positions. 

current pool tick = 0

```
await NonfungiblePositionManager.mint({
  ...
  tickLower: -2880,
  tickUpper: -1440,
  amount0Desired: 1e18,
  amount1Desired: 1e18,
  ...
});
```

and I get the following output from the IncreaseLiquidity event;

```
tokenId = 648349
liquidity = 15470233979090984205n
amount0 = 0
amount1 = 1000000000000000000n
```

then I mint the next position (with current pool tick = 0)

```
await NonfungiblePositionManager.mint({
  ...
  tickLower: 0,
  tickUpper: 60,
  amount0Desired: 1e18,
  amount1Desired: 1e18,
  ...
});
```

```
tokenId = 648350
liquidity = 333850249709699449134
amount0 = 1000000000000000000
amount1 = 0
```

So these positions are fine.

However, if I change it up and mint that second position using `IUniV3Automan.mintOptimal()` then I get a "Transaction ran out of gas". If I just try the `getOptimalSwap()` method then that crashes, so its this part that is causing the issue. 

I haven't been able to work out what the exact conditions are that cause the issue as I can mint with some tick ranges and it will work perfectly. For example, I can do the following 

```
await NonfungiblePositionManager.mintOptimal({
  ...
  tickLower: -60,
  tickUpper: 0,
  amount0Desired: 1e18,
  amount1Desired: 1e18,
  ...
});
```

So I'm not sure if it has something to do with minting liquidity on the other side of the tick if there is no liquidity in that area.

Are there any known limitations to this?

**Comment by gnarlycow** [comment]
Could you please share the script where you create a Hardhat fork and run into issues with Automan's `mintOptimal()` transactions?  It would be great if you can make it deterministic and reproducible by specifying a block number to fork from.

**Comment by cosullivan** [comment]
I've created a sample project using Hardhat forked against block 19012733 on Ethereum which shows the issue.
https://github.com/cosullivan/automan-test

When I run this test script with a hardhat node running I can see the error in the hardhart node's console and it runs out of gas.
Gas used: 29999986 of 30000000

**Comment by gnarlycow** [comment]
Your script initializes the pool price to 1, i.e. tick 0.  Then, it sets up a position from tick -2880 to -1440, making this a single-sided (out of range) position; you can see below that only token1 liquidity is provided there.

> minting first liquidity position
> tokenId 648349n
> liquidity 15470233979090984205n
> amount0 0n
> amount1 1000000000000000000n

And then, you try to use `optimalSwap` to set up a position from tick 60 to 1440 which is on the other side of the pool current tick of 0, so it only wants liquidity in token0.  `optimalMint` would have to swap all provided token1 for token0 before it can provide liquidity, but since the pool doesn't have any active liquidity, no swap could be performed.  That's why the `optimalMint` tx fails.

If you change the initial position's range to something like from tick -2880 to +2880, then try to `optimalMint` a position from tick 6000 to 6600, you'll see it works.

**Comment by cosullivan** [comment]
Hi, thanks for the quick response.

I realise that my data here is contrived, but my issue is more that the getOptimalSwap method (under these conditions) seems to either enter an infinite loop, or have to do too much work that it consumes too much gas and fails.

So what is the precondition that needs to be checked for before calling getOptimalSwap?

**Comment by gnarlycow** [comment]
The method assumes that either the pool has enough liquidity to support the swap, or a swap path is provided to route through an aggregator like 1inch.  Due to our desire to minimize gas cost for the most common case, we didn't do a pool liquidity check before the main business logic so that's likely why it consumes a lot of gas.  Hope that helps!
